### ISSUE TITLE
AssertionError: Embedding dim mismatch, expected: 768, but loaded: 1536 when running ollama demo file

### ISSUE THREAD

**Issue by s-github-2** [HKUDS/LightRAG#355]
demo example with ollama gives the error
AssertionError: Embedding dim mismatch, expected: 768, but loaded: 1536
changed the parameter to 1536 from the default 768 and then got a different error

the last lines from the output are below
Generating embeddings: 100%|██████████████████████████████████████████████████████████| 2/2 [00:40<00:00, 20.39s/batch]
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "D:\Github\LightRAG\examples\lightrag_ollama_demo.py", line 35, in <module>
    rag.insert(f.read())
  File "d:\github\lightrag\lightrag\lightrag.py", line 225, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "c:\Users\sjsha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\github\lightrag\lightrag\lightrag.py", line 273, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "d:\github\lightrag\lightrag\storage.py", line 112, in upsert
    results = self._client.upsert(datas=list_data)
  File "c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nano_vectordb\dbs.py", line 100, in upsert
    self.__storage["matrix"][i] = update_d[f_VECTOR].astype(Float)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by s-github-2** [comment]
deleted the dickens folder created earlier by an incomplete execution of the example script and this seems to have fixed at leat the initial error issue. Rerunning the ollama demo script now, its proceeding further instead of erroring out at the load model with the above error

**Comment by j-shah7** [comment]
Hi i have used other working directory still showing the same error. Can you please tell me how you have resolved the error? Thanks

**Comment by j-shah7** [comment]
Hi i am getting the same error message. can any one help me in this regard how to resolve this error? Thanks
