### ISSUE TITLE
got "missing 1 required positional argument: 'content'" error when trying to re-run from last time failure

### ISSUE THREAD

**Issue by Johnny987** [HKUDS/LightRAG#747]
I tried Rag batch insert 22 files(each batch 10 files by default), but the scripts were hanging on Batch 2 20% for 24 hrs, so I canceled the script and tried to re-run the script.
It recognizes there are 13 docs already extracted in storage and 9 new docs added(those might be in Batch2&3 and haven't extracted)
```
_INFO:Loaded document status storage with 13 records
INFO:Stored 9 new unique documents
```
But then it shows the error:
`TypeError: DocProcessingStatus.__init__() missing 1 required positional argument: 'content'`

This is my batch insert code:
```
# Batch insert documents
textList = []
for filename in os.listdir(input_dir):
    if filename.endswith('.txt'):
        with open(os.path.join(input_dir, filename), "r", encoding="utf-8") as f:
            textList.append(f.read())
rag.insert(textList)
```
Not sure why it works the first time, but instead, I got a 'missing content' error when I re-ran it. Do I have to clean the WORK_DIR? It took an insanely long time almost 30 hours for me to extract the first 13 docs. I hate re-running all of them....

And one more question: How do I know which documents have already been extracted and which have not?

**Comment by LarFii** [comment]
You can check the `kv_store_doc_status.json` file to identify which documents have already been processed. For the error you're encountering, it has been fixed in the latest code.  Since the processing of other files hasn't changed, you can simply re-insert the documents that haven't been processed yet.

**Comment by TaulantAsllani** [comment]
i still get the same error when running the lightRAG server and doing api calls for inserting text or uploading a txt document. Last time I tried it, it was working fine.

**Comment by LarFii** [comment]
> Yes, I did checked the `kv_store_doc_status.json` file, the documents are renamed as something like "doc-19907d7c98ea5b4da2c37fd659429be2", how can I relate them to the original file?

In the `kv_store_full_docs.json`, you can find the mapping to the original documents.

**Comment by LuyiTian** [comment]
Hi @Johnny987 I got the same error and I looked at the source code. I found there are duplicate checking in the insert function: https://github.com/HKUDS/LightRAG/blob/4d58ff8bb4fcb4863634fe3a21ed0130140c75a9/lightrag/lightrag.py#L680C15-L680C42. with this line: unique_new_doc_ids = await self.doc_status.filter_keys(all_new_doc_ids). However, when I dive in and check how filter_keys works, I found an unimplementated function: https://github.com/HKUDS/LightRAG/blob/4d58ff8bb4fcb4863634fe3a21ed0130140c75a9/lightrag/base.py#L120


so a dirty fix that I did is to remove this checking process, although you need to make sure you are not adding duplicated document. I am not sure what will happen if you remove this line and adding the same document multiple times, will it create multiple copys in the json file? I assume they have the same hash key and if json is stored in dict it wont create duplicates.

**Comment by Johnny987** [comment]
> > Yes, I did checked the `kv_store_doc_status.json` file, the documents are renamed as something like "doc-19907d7c98ea5b4da2c37fd659429be2", how can I relate them to the original file?
> 
> In the `kv_store_full_docs.json`, you can find the mapping to the original documents.

I don't see any mapping for doc-<random_id> with its name in `kv_store_full_docs.json` either. They all use doc-<random_id> and contain the same chunk information, in `kv_store_doc_status.json` might with additional "status", "chunks_count", "content_summary" etc.
